# coding: utf-8

"""
    Gotyai API v3

    Gotyai API : the Spartan explainable AI   # noqa: E501

    The version of the OpenAPI document: 3.0.2
    Contact: contact@namsor.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from gotyai_client import schemas  # noqa: F401


class APIUsageHistoryOut(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            
            
            class detailedUsage(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['APICounterV2Out']:
                        return APICounterV2Out
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['APICounterV2Out'], typing.List['APICounterV2Out']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'detailedUsage':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'APICounterV2Out':
                    return super().__getitem__(i)
            __annotations__ = {
                "detailedUsage": detailedUsage,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["detailedUsage"]) -> MetaOapg.properties.detailedUsage: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["detailedUsage", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["detailedUsage"]) -> typing.Union[MetaOapg.properties.detailedUsage, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["detailedUsage", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        detailedUsage: typing.Union[MetaOapg.properties.detailedUsage, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'APIUsageHistoryOut':
        return super().__new__(
            cls,
            *_args,
            detailedUsage=detailedUsage,
            _configuration=_configuration,
            **kwargs,
        )

from gotyai_client.model.api_counter_v2_out import APICounterV2Out
