# coding: utf-8

"""
    Gotyai API v3

    Gotyai API : the Spartan explainable AI   # noqa: E501

    The version of the OpenAPI document: 3.0.2
    Contact: contact@namsor.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from gotyai_client import schemas  # noqa: F401


class BillingHistoryOut(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            
            
            class stripeInvoices(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['InvoiceOut']:
                        return InvoiceOut
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['InvoiceOut'], typing.List['InvoiceOut']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'stripeInvoices':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'InvoiceOut':
                    return super().__getitem__(i)
            
            
            class corporateInvoices(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['InvoiceOut']:
                        return InvoiceOut
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['InvoiceOut'], typing.List['InvoiceOut']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'corporateInvoices':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'InvoiceOut':
                    return super().__getitem__(i)
            __annotations__ = {
                "stripeInvoices": stripeInvoices,
                "corporateInvoices": corporateInvoices,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["stripeInvoices"]) -> MetaOapg.properties.stripeInvoices: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["corporateInvoices"]) -> MetaOapg.properties.corporateInvoices: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["stripeInvoices", "corporateInvoices", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["stripeInvoices"]) -> typing.Union[MetaOapg.properties.stripeInvoices, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["corporateInvoices"]) -> typing.Union[MetaOapg.properties.corporateInvoices, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["stripeInvoices", "corporateInvoices", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        stripeInvoices: typing.Union[MetaOapg.properties.stripeInvoices, list, tuple, schemas.Unset] = schemas.unset,
        corporateInvoices: typing.Union[MetaOapg.properties.corporateInvoices, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BillingHistoryOut':
        return super().__new__(
            cls,
            *_args,
            stripeInvoices=stripeInvoices,
            corporateInvoices=corporateInvoices,
            _configuration=_configuration,
            **kwargs,
        )

from gotyai_client.model.invoice_out import InvoiceOut
