# coding: utf-8

"""
    Gotyai API v3

    Gotyai API : the Spartan explainable AI   # noqa: E501

    The version of the OpenAPI document: 3.0.2
    Contact: contact@namsor.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from gotyai_client import schemas  # noqa: F401


class SpamStatsOut(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            
            
            class spams(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['SpamEventOut']:
                        return SpamEventOut
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['SpamEventOut'], typing.List['SpamEventOut']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'spams':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'SpamEventOut':
                    return super().__getitem__(i)
            durationMillis = schemas.Int64Schema
            spam = schemas.Int32Schema
            nonSpam = schemas.Int32Schema
            __annotations__ = {
                "spams": spams,
                "durationMillis": durationMillis,
                "spam": spam,
                "nonSpam": nonSpam,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["spams"]) -> MetaOapg.properties.spams: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["durationMillis"]) -> MetaOapg.properties.durationMillis: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["spam"]) -> MetaOapg.properties.spam: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nonSpam"]) -> MetaOapg.properties.nonSpam: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["spams", "durationMillis", "spam", "nonSpam", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["spams"]) -> typing.Union[MetaOapg.properties.spams, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["durationMillis"]) -> typing.Union[MetaOapg.properties.durationMillis, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["spam"]) -> typing.Union[MetaOapg.properties.spam, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nonSpam"]) -> typing.Union[MetaOapg.properties.nonSpam, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["spams", "durationMillis", "spam", "nonSpam", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        spams: typing.Union[MetaOapg.properties.spams, list, tuple, schemas.Unset] = schemas.unset,
        durationMillis: typing.Union[MetaOapg.properties.durationMillis, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        spam: typing.Union[MetaOapg.properties.spam, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        nonSpam: typing.Union[MetaOapg.properties.nonSpam, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SpamStatsOut':
        return super().__new__(
            cls,
            *_args,
            spams=spams,
            durationMillis=durationMillis,
            spam=spam,
            nonSpam=nonSpam,
            _configuration=_configuration,
            **kwargs,
        )

from gotyai_client.model.spam_event_out import SpamEventOut
