# coding: utf-8

"""
    Gotyai API v3

    Gotyai API : the Spartan explainable AI   # noqa: E501

    The version of the OpenAPI document: 3.0.2
    Contact: contact@namsor.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import gotyai_client
from gotyai_client.model.cache_metrics_out import CacheMetricsOut
from gotyai_client import configuration


class TestCacheMetricsOut(unittest.TestCase):
    """CacheMetricsOut unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
