# coding: utf-8

# flake8: noqa

"""
    Gotyai API v3

    Gotyai API : the Spartan explainable AI   # noqa: E501

    The version of the OpenAPI document: 3.0.2
    Contact: contact@namsor.com
    Generated by: https://openapi-generator.tech
"""

__version__ = "3.0.2"

# import ApiClient
from gotyai_client.api_client import ApiClient

# import Configuration
from gotyai_client.configuration import Configuration

# import exceptions
from gotyai_client.exceptions import OpenApiException
from gotyai_client.exceptions import ApiAttributeError
from gotyai_client.exceptions import ApiTypeError
from gotyai_client.exceptions import ApiValueError
from gotyai_client.exceptions import ApiKeyError
from gotyai_client.exceptions import ApiException
